version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - streamflow-network

  video_db:
    image: postgres:17-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: video_db
      POSTGRES_USER: video-user
      POSTGRES_PASSWORD: video-password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - streamflow-network

  video-search:
    image: elasticsearch:9.1.4
    environment:
      - discovery.type=single-node
      - node.name=video-search
      - discovery.seed_hosts=video-search
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - streamflow-network

  logstash:
    image: logstash:9.1.4
    ports:
      - "5044:5044"
    depends_on:
      - video_db
      - video-search
    environment:
      - PIPELINE_WORKERS=1
      - PIPELINE_BATCH_SIZE=125
      - PIPELINE_BATCH_DELAY=50
    volumes:
      - ./conf/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash_data:/usr/share/logstash/data
      - ./conf/postgresql-42.6.0.jar:/usr/share/logstash/postgresql-42.6.0.jar
    networks:
      - streamflow-network

  kibana:
    image: kibana:9.1.4
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      ELASTICSEARCH_URL: http://video-search:9200
      ELASTICSEARCH_HOSTS: http://video-search:9200
    networks:
      - streamflow-network


volumes:
  elasticsearch_data:
  postgres_data:
  redis_data:
  logstash_data:

networks:
  streamflow-network:
    driver: bridge
